var d = new Date();
var m  = d.getMonth();
var months = ["January", "Februrary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
m = months[m];
document.querySelector("h1#month").innerHTML = m;
var day = 1;
var row = 1;
var specificDate = new Date(d.getFullYear(), d.getMonth(), day);
var tableCells = document.querySelectorAll("td#row" + row);
tableCells[specificDate.getDay()].innerHTML = day;
day++;
